VAGRANTFILE_API_VERSION = "2"

cluster = {
  "c1-cp1" => { :ip => "192.168.1.10", :cpus => 2, :memory => 2048 },
  "c1-node1" => { :ip => "192.168.1.11", :cpus => 2, :memory => 2048 },
  "c1-node2" => { :ip => "192.168.1.12", :cpus => 2, :memory => 2048 },
  "c1-node3" => { :ip => "192.168.1.13", :cpus => 2, :memory => 2048 },
}

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
  cluster.each_with_index do |(hostname, info), index|
    config.vm.define hostname do |cfg|
      cfg.vm.box = "bento/ubuntu-20.04"
      cfg.vm.hostname = hostname
      cfg.vm.network :private_network, ip: info[:ip]
      cfg.vm.provider :virtualbox do |vb|
        vb.name = hostname
        vb.cpus = info[:cpus]
        vb.memory = info[:memory]
        vb.customize ["modifyvm", :id, "--hwvirtex", "on"]
      end # end of vb
    end # end cfg
  end # end cluster
end
